// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVjyiSm2MYvMFKT1nDmY2z-rqWJYwbhl0',
    appId: '1:507657497619:web:b5a264fb5b410b6953e3e6',
    messagingSenderId: '507657497619',
    projectId: 'diplomaprj-290fd',
    authDomain: 'diplomaprj-290fd.firebaseapp.com',
    storageBucket: 'diplomaprj-290fd.firebasestorage.app',
    measurementId: 'G-7C1X35FPLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX7-ei_Z-ngJu0Lf7ieoqRpadcnNGC5xs',
    appId: '1:507657497619:android:73cfe208f3bcc36953e3e6',
    messagingSenderId: '507657497619',
    projectId: 'diplomaprj-290fd',
    storageBucket: 'diplomaprj-290fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhzosy-A3nJ8PRvLJSs-a8DFzmUzcJmRc',
    appId: '1:507657497619:ios:341fb0a4d6fa5f5f53e3e6',
    messagingSenderId: '507657497619',
    projectId: 'diplomaprj-290fd',
    storageBucket: 'diplomaprj-290fd.firebasestorage.app',
    iosBundleId: 'com.example.diplomaPrj',
  );

}